9-user-management
vanyaserdyuk/TestTaskWithMongo pull request #21
Opened 2020-11-11 22:19 UTC by vanyaserdyuk

2020-11-16 12:08 UTC, iv21dk requested changes

2020-11-16 12:08 UTC, iv21dk commented on src/main/java/ru/testtask/controller/UserController.java
> +        Optional<User> optionalUser = userService.getUserById(id);
It isn't good idea to transfer to client all user data (with password). It is better to use some DTO object.

2020-11-16 12:08 UTC, iv21dk commented on src/main/java/ru/testtask/controller/UserController.java
> +        User user = userService.getUserByUsername(name);
It isn't good idea to transfer to client all user data (with password). It is better to use some DTO object.

2020-11-16 12:08 UTC, iv21dk commented on src/main/java/ru/testtask/controller/UserController.java
> +        List<User> users = userService.getAllUsers();
It isn't good idea to transfer to client all user data (with password). It is better to use some DTO object.

2020-11-16 12:08 UTC, iv21dk commented on src/main/java/ru/testtask/service/UserService.java
> +        createDefaultUser("user", "$2y$12$/wwVf0mDfYo4IRIT2jd0a.ks4wu/f7Np/NrGZJ6rxXUjG5UOs.Lb2", Collections.singleton(Role.USER));
It is better to use `createUser(User user)` method instead using encoded password. You can add new parameter `boolean checkName` into  `createUser(User user)` to avoid repeated call getUserByUsername(user.getUsername())

2020-11-16 12:08 UTC, iv21dk commented on src/test/java/ru/testtask/controller/UserControllerTest.java
> +                        get("/api/projects/a"))
Incorrect url of request

2020-11-16 12:08 UTC, iv21dk commented on src/test/java/ru/testtask/controller/UserControllerTest.java
> +                .andExpect(MockMvcResultMatchers.jsonPath("$.name").value("user"));
It is bette to check "roles" field too

2020-11-16 12:08 UTC, iv21dk commented on src/test/java/ru/testtask/controller/UserControllerTest.java
> +                .andExpect(MockMvcResultMatchers.jsonPath("$.name").value("user"));
It is bette to check "roles" field too

2020-11-16 13:32 UTC, vanyaserdyuk commented on src/main/java/ru/testtask/controller/UserController.java
> +        Optional<User> optionalUser = userService.getUserById(id);
Я тоже думал над этим, но подумал, что админ должен видеть всю информацию, мы же не даем другим доступ

2020-11-17 11:33 UTC, iv21dk requested changes

2020-11-17 11:33 UTC, iv21dk commented on src/main/java/ru/testtask/controller/UserController.java
>      @PreAuthorize("hasAuthority('ADMIN')")
Aggreed to use config instead `@PreAuthorize("hasAuthority('ADMIN')")` for all methods

2020-11-17 11:33 UTC, iv21dk commented on src/main/java/ru/testtask/dto/UserDTO.java
>  public class UserDTO {
In my opinion it is better to rename to `CreateUpdateUserDTO`. This can extends `ViewUserDTO`

2020-11-17 11:33 UTC, iv21dk commented on src/main/java/ru/testtask/dto/ViewUserDTO.java
> +public class ViewUserDTO {
In my opinion it is better to rename to `UserDTO`

2020-11-17 11:33 UTC, iv21dk commented on src/main/java/ru/testtask/service/UserService.java
> +        objectMapper.enable(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY);
It is better to use some config class

2020-11-17 11:33 UTC, iv21dk commented on src/main/java/ru/testtask/controller/UserController.java
> +        for (User user : users) {
It is better to use stream to transform one collection to another

2020-11-18 12:00 UTC, iv21dk requested changes

2020-11-18 12:00 UTC, iv21dk commented on src/main/java/ru/testtask/config/ObjectMapperConfig.java
> +        objectMapper.enable(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY);
I think it isn't necessary to enable this feature

2020-11-18 12:00 UTC, iv21dk commented on src/main/java/ru/testtask/config/WebSecurityConfig.java
> +                antMatchers("/api/projects/**").authenticated().
`/api/**` instead `/api/projects/**`

2020-11-18 12:00 UTC, iv21dk commented on src/main/java/ru/testtask/config/WebSecurityConfig.java
> +                antMatchers("/api/projects/**").authenticated().
```
        http.csrf().disable().authorizeRequests()
            .antMatchers("/api/users/**").access("hasAuthority('ADMIN')")
            .antMatchers("/api/projects/**").authenticated()
            .and().httpBasic()
            .and().sessionManagement().disable();

```
more visual

2020-11-18 12:00 UTC, iv21dk commented on src/main/java/ru/testtask/controller/UserController.java
> +        if (users.isEmpty()) {
Empty list is better than error status

2020-11-18 12:00 UTC, iv21dk commented on src/main/java/ru/testtask/service/UserService.java
>                  log.error("Impossible to write this user to a database");
You will see ERROR message all of time during starting the server

2020-11-18 12:43 UTC, iv21dk requested changes

2020-11-18 12:43 UTC, iv21dk commented on src/test/java/ru/testtask/controller/UserControllerTest.java
> +                        .content(objectMapper.writeValueAsString(user))
You need to use `CreateUpdateUserDTO` here

2020-11-18 12:43 UTC, iv21dk commented on src/test/java/ru/testtask/controller/UserControllerTest.java
> +                        .content(objectMapper.writeValueAsString(user))
You need to use `CreateUpdateUserDTO` here

2020-11-18 14:09 UTC, iv21dk requested changes

2020-11-18 14:09 UTC, iv21dk commented on src/main/java/ru/testtask/controller/UserController.java
>              return new ResponseEntity<>(user, HttpStatus.OK);
`UserDto` should be returned

2020-11-18 14:09 UTC, iv21dk commented on src/main/java/ru/testtask/controller/UserController.java
> +            return new ResponseEntity<>(modelMapper.map(userService.createUser(user), CreateUpdateUserDTO.class), HttpStatus.CREATED);
`UserDto` should be returned

2020-11-19 13:24 UTC, merged